version: "3.9"

services:
  db:
    container_name: postgres
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
    # M1チップでも動くように
    platform: linux/x86_64
    # ローカルの/data/dbをコンテナの/var/lib/mysqlにマウンティング
    volumes:
      - db_data:/var/lib/postgresql/data
    # 環境変数
    env_file:
      - .env
  app:
    container_name: app
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    command: sh -c "entrypoint.sh"
    volumes:
      - .:/code
      - ./static:/static
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - db
  web:
    container_name: web
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    volumes:
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  db_data:
  static:
